### ISSUE TITLE
Not seeing IGB

### ISSUE THREAD

**Issue by Hightech1011** [jeremieroy/EVELiveIntel#3]
I have an issue when trying to access the map from the IGB, it tells me that I need to login using the IGB.

The site is in my trusted list.

**Comment by jeremieroy** [comment]
Hi Hightech1011,
I unfortunately left Eve more than a year ago :/
It is possible CCP changed something with the IGB, and I have no way to try/debug it.
That being said:
It is probably some kind of Apache (2.4+) configuration issue:
see:
https://forums.eveonline.com/default.aspx?g=posts&t=215730
Or search HTTP_EVE TRUSTED  in google.

In my case I used a workaround visible in the .htaccess 
https://github.com/jeremieroy/EVELiveIntel/blob/master/website/.htaccess

Which is nearly a direct copy/paste from the thread below:
http://eve-search.com/thread/249946-1/page/1

I hope that helps :/

**Comment by jeremieroy** [comment]
@Hightech1011 Hi, was your issue solved ?
